export const localTheme = {
  chatBG: "#F3F6FB",
  profileBG: "#D4E6F6",
  userListBG: "#F3F6FB",
  userListBGHover: "rgba(243, 246, 251, 0.7)",
  messageBG: "#1B233C",
  buttonBG: "#1A4FFF",
  timeIconBG: "#B0C6FF",
  timeOuter: "#1854FF",
  timeBG: "#DAE4FE",
  attendedBG: "#E3F6F3",
  attemdedOuter: "#1DBD9E",
  attendedIconBG: "#C7F0E9",
  meetingsBG: "#F7F3FF",
  meetingsOuter: "#8375CF",
  meetingsIconBG: "#D8D2FF",
  rejectedBG: "#FEF1E9",
  rejectedOuter: "#FB6C4A",
  rejectedIconBG: "#FEE1D4",
  metricesBG: "#F9FAFD",
  borderColor: "#EDF2F8",
};
